import type { VercelRequest, VercelResponse } from '@vercel/node';
import { GoogleGenAI } from '@google/genai';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const { image, prompt } = req.body;
    if (!image || !prompt) return res.status(400).json({ error: 'Image and prompt required' });

    const matches = image.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/);
    if (!matches) return res.status(400).json({ error: 'Invalid image format' });
    const mimeType = matches[1];
    const base64Data = matches[2];

    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-preview-05-20',
      contents: {
        parts: [
          { inlineData: { data: base64Data, mimeType } },
          { text: prompt }
        ]
      }
    });

    let generatedImage: string | null = null;
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if ((part as any).inlineData) {
        generatedImage = `data:image/png;base64,${(part as any).inlineData.data}`;
        break;
      }
    }

    if (!generatedImage) throw new Error('No image generated by Gemini');

    // Deduct credit via cookie
    const current = parseInt(req.cookies?.ss_credits ?? '3', 10);
    res.setHeader('Set-Cookie', `ss_credits=${Math.max(0, current - 1)}; Path=/; Max-Age=2592000; SameSite=Lax`);

    res.json({ success: true, generatedImage, engine: 'gemini' });
  } catch (error: any) {
    console.error('Gemini stage error:', error);
    res.status(500).json({ error: error.message || 'Failed to generate image' });
  }
}
